# Generated by Django 6.0.4 on 2026-04-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'HR')], default='TECHNICAL', max_length=20)),
                ('category', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'JavaScript'), ('REACT', 'React'), ('GENERAL', 'General'), ('HR', 'HR')], default='GENERAL', max_length=50)),
                ('difficulty', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='ACTIVE', max_length=20)),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'HR')], default='TECHNICAL', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend')], max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], max_length=20, null=True)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('final_overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_ai_feedback', models.JSONField(blank=True, null=True)),
                ('final_feedback_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question_kind', models.CharField(choices=[('BASE', 'Base'), ('FOLLOW_UP', 'Follow-up')], default='BASE', max_length=20)),
                ('display_text', models.TextField(blank=True, null=True)),
                ('created_by_ai', models.BooleanField(default=False)),
                ('parent_session_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='interviews.sessionquestion')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='interviews.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='interviews.session')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('ai_needs_followup', models.BooleanField(default=False)),
                ('ai_followup_question', models.TextField(blank=True, null=True)),
                ('ai_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.sessionquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_question_order_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_question_per_session'),
        ),
    ]
