# Generated by Django 6.0.4 on 2026-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='bonus_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('CONCEPTUAL', 'Conceptual'), ('PRACTICAL', 'Practical'), ('DEBUGGING', 'Debugging'), ('ARCHITECTURE', 'Architecture'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Security'), ('TRADE_OFF', 'Trade-off')], default='CONCEPTUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='technology',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'JavaScript'), ('TYPESCRIPT', 'TypeScript'), ('REACT', 'React'), ('PYTHON', 'Python'), ('DJANGO', 'Django'), ('REST_API', 'REST API'), ('SQL', 'SQL'), ('AUTHENTICATION', 'Authentication'), ('SECURITY', 'Security'), ('TESTING', 'Testing'), ('PERFORMANCE', 'Performance'), ('ACCESSIBILITY', 'Accessibility'), ('GENERAL', 'General'), ('HR', 'HR')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='track',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('FULLSTACK', 'Fullstack'), ('GENERAL', 'General')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='session',
            name='selected_technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='session',
            name='role',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('FULLSTACK', 'Fullstack')], max_length=50, null=True),
        ),
    ]
